### ISSUE TITLE
要是能支持下edge就好了

### ISSUE THREAD

**Issue by Coloryr** [project-mirai/mirai-login-solver-selenium#17]
win10 习惯用edge
```
[92m2021-02-03 19:57:54 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m
Line:     ProgId    REG_SZ    MSEdgeHTM, b64:ICAgIFByb2dJZCAgICBSRUdfU1ogICAgTVNFZGdlSFRN
List: [, ProgId, REG_SZ, MSEdgeHTM]
Line:     AppUserModelId    REG_SZ    MSEdge, b64:ICAgIEFwcFVzZXJNb2RlbElkICAgIFJFR19TWiAgICBNU0VkZ2U=
List: [, AppUserModelId, REG_SZ, MSEdge]
Line:     ApplicationIcon    REG_SZ    C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe,0, b64:ICAgIEFwcGxpY2F0aW9uSWNvbiAgICBSRUdfU1ogICAgQzpcUHJvZ3JhbSBGaWxlcyAoeDg2KVxNaWNyb3NvZnRcRWRnZVxBcHBsaWNhdGlvblxtc2VkZ2UuZXhlLDA=
List: [, ApplicationIcon, REG_SZ, C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe,0]
Line:     ApplicationName    REG_SZ    Microsoft Edge, b64:ICAgIEFwcGxpY2F0aW9uTmFtZSAgICBSRUdfU1ogICAgTWljcm9zb2Z0IEVkZ2U=
List: [, ApplicationName, REG_SZ, Microsoft Edge]
Line:     ApplicationDescription    REG_SZ    浏览 Web, b64:ICAgIEFwcGxpY2F0aW9uRGVzY3JpcHRpb24gICAgUkVHX1NaICAgIOa1j+iniCBXZWI=
List: [, ApplicationDescription, REG_SZ, 浏览 Web]
Line:     ApplicationCompany    REG_SZ    Microsoft Corporation, b64:ICAgIEFwcGxpY2F0aW9uQ29tcGFueSAgICBSRUdfU1ogICAgTWljcm9zb2Z0IENvcnBvcmF0aW9u
List: [, ApplicationCompany, REG_SZ, Microsoft Corporation]
[91m2021-02-03 19:57:54 W/Mirai: Error in loading mirai-login-solver-selenium, skip
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$SeleniumLoginSolver$2.invoke(SeleniumLoginSolverSupport.kt:19)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$SeleniumLoginSolver$2.invoke(SeleniumLoginSolverSupport.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt.getSeleniumLoginSolver(SeleniumLoginSolverSupport.kt)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$isSliderCaptchaSupportKind$2.invoke(SeleniumLoginSolverSupport.kt:35)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt$isSliderCaptchaSupportKind$2.invoke(SeleniumLoginSolverSupport.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.utils.SeleniumLoginSolverSupportKt.isSliderCaptchaSupportKind(SeleniumLoginSolverSupport.kt)
        at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.kt:97)
        at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:123)
        at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:291)
        at Color_yr.ColorMirai.Robot.BotStart.Start(BotStart.java:30)
        at Color_yr.ColorMirai.Start.main(Start.java:35)
Caused by: java.lang.RuntimeException: Exception in loading selenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        ... 17 more
Caused by: java.lang.UnsupportedOperationException: Unsupported browser: MSEdgeHTM, Only chrome/firefox supported
        at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$4(MxSelenium.java:245)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:352)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:63)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:31)
        ... 21 more
[0m
```

**Comment by Karlatemp** [comment]
看过，MSEdgeHTM 不支持设置 UserAgent
