### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wqy0916** [project-mirai/mirai-login-solver-selenium#2]
```
2020-12-29 08:06:11 I/main: Starting mirai-console...
2020-12-29 08:06:11 I/main: Backend: version 2.0-M2, built on 2020-12-28 18:39:29.
2020-12-29 08:06:11 I/main: Frontend Terminal: version 2.0-M2, provided by Mamoe Technologies
2020-12-29 08:06:11 I/plugin: Successfully loaded plugin MiraiNative
2020-12-29 08:06:11 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-12-29 08:06:12 I/MiraiNative: 正在加载 Mirai Native Bridge C:\Users\小冰酱丷\Desktop\mirai2.0\mirai2.0-M2\data\MiraiNative\CQP.dll
2020-12-29 08:06:12 I/main: 1 plugin(s) enabled.
2020-12-29 08:06:12 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2020-12-29 08:06:12 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2020-12-29 08:06:12 I/main: Auto-login 2771733267
2020-12-29 08:06:12 I/Bot.2771733267: Logging in...
2020-12-29 08:06:13 W/Bot.2771733267: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at io.github.karlatemp.unsafeaccessor.Open9.open(Open9.java:89)
        at io.github.karlatemp.unsafeaccessor.UsfAccessor.allocateUnsafe(UsfAccessor.java:16)
        at io.github.karlatemp.unsafeaccessor.Unsafe.getUnsafe(Unsafe.java:94)
        at io.github.karlatemp.unsafeaccessor.Unsafe.<clinit>(Unsafe.java:710)
        at io.github.karlatemp.unsafeaccessor.Root.getUnsafe(Root.java:18)
        at io.github.karlatemp.unsafeaccessor.Root$RootLookupHolder.<clinit>(Root.java:42)
        at io.github.karlatemp.unsafeaccessor.Root.getTrusted(Root.java:23)
        at io.github.karlatemp.mxlib.reflect.Reflections.<clinit>(Reflections.java:26)
        at io.github.karlatemp.mxlib.common.utils.IOUtils.<clinit>(IOUtils.java:21)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:108)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:103)
        at io.github.karlatemp.mxlib.selenium.WindowsKit.queryBrowserUsing(WindowsKit.java:42)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:123)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:222)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.ClassNotFoundException: jdk.internal.access.JavaLangAccess
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.github.karlatemp.unsafeaccessor.Open9.open(Open9.java:79)
        ... 17 more

2020-12-29 08:06:13 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:13 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:13 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:18 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:18 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:18 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

2020-12-29 08:06:18 W/Bot.2771733267: java.lang.NullPointerException
java.lang.NullPointerException
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
```

core版本为2.0-M2
console版本为2.0M2
java版本openjdk11
系统win10

**Comment by Him188** [comment]
请问你使用的是哪个 JDK

**Comment by wqy0916** [comment]
openjdk11
