### ISSUE TITLE
JDK11发送报错

### ISSUE THREAD

**Issue by YuKanJiu** [project-mirai/mirai-login-solver-selenium#21]
``2021-02-09 16:53:34 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-selenium is not supported.
java.lang.RuntimeException: Exception in loading selenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:32)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:108)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:152)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.UnsupportedOperationException: Unsupported browser: MSEdgeHTM, Only chrome/firefox supported
        at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$4(MxSelenium.java:245)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:352)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:63)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:31)
        ... 44 more

2021-02-09 16:53:34 W/net.mamoe.mirai-login-solver-selenium: Using HttpProxyServer mode

**Comment by CryChow** [comment]
同样问题 楼主解决了不
