### ISSUE TITLE
firefox对接错误

### ISSUE THREAD

**Issue by liaosunny123** [project-mirai/mirai-login-solver-selenium#23]
最新版本的firefox并不能完成对接，相反chrome可以对接，两者均在默认浏览器下操作。
at org.openqa.selenium.firefox.FirefoxOptions.getBinart(FirefoxOptions.java:199)

**Comment by Karlatemp** [comment]
完整报错? 而且这属于 selenium 问题， mirai-login-solver-selenium 可能无法处理

**Comment by liaosunny123** [comment]
![1613054331816](https://user-images.githubusercontent.com/30096937/107650924-f039c700-6cb9-11eb-8150-fa90e547035b.jpg)

**Comment by Karlatemp** [comment]
你能 `Ctrl+A`, `Ctrl+C`, `Ctrl+V` 吗

**Comment by StageGuard** [comment]
![E{KKR@ ~ BGHX9A9KEFEM%7](https://user-images.githubusercontent.com/45701251/107654382-92a77980-6cbd-11eb-96ad-5db811d89b1f.jpg)

**Comment by liaosunny123** [comment]
这个是我用户错误的时候提供的log文件笑哭，log文件在提供截图的时候已经在要了，等会提交一下。

**Comment by liaosunny123** [comment]
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:95)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:199)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.withOptions(GeckoDriverService.java:180)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:177)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$firefox$13(MxSelenium.java:362)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:380)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:85)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:48)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:27)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by liaosunny123** [comment]
[92m2021-02-11 15:29:04 I/Net [脱敏]: Connected to server 114.221.144.89:80[0m
[0m2021-02-11 15:29:04 V/Net [脱敏]: Send: wtlogin.login[0m
[0m2021-02-11 15:29:04 V/Net [脱敏]: Recv: LoginPacketResponse.Captcha.Slider[0m
[92m2021-02-11 15:29:04 I/Net [脱敏]: Connected to server 14.22.3.51:8080[0m
[0m2021-02-11 15:29:04 V/Net [脱敏]: Send: wtlogin.login[0m
[0m2021-02-11 15:29:04 V/Net [脱敏]: Recv: LoginPacketResponse.Captcha.Slider[0m
[91m2021-02-11 15:29:04 W/Net [脱敏]: org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'DESKTOP-DSOEUJK', ip: '192.168.0.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'DESKTOP-DSOEUJK', ip: '192.168.0.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:95)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:199)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.withOptions(GeckoDriverService.java:180)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:177)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$firefox$13(MxSelenium.java:362)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:380)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:85)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:48)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:27)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by liaosunny123** [comment]
好像是FireFox获取不到，但是确实安装了他
