### ISSUE TITLE
mirai-login-solver-selenium is not supported

### ISSUE THREAD

**Issue by Catoverflow** [project-mirai/mirai-login-solver-selenium#32]
运行环境：
Linux 5.11.16-arch1-1
mirai-console-terminal 2.6.2
mirai-console 2.6.2
mirai-login-solver-selenium 1.0-dev-17
在启动 mcl 的加载过程中出现报错
报错信息：
~~~~java
2021-04-26 15:00:10 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-selenium is not supported. 
java.lang.RuntimeException: Exception in loading selenium                                               
     at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:33)                           
     at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)                    
     at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)                      
     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                                             
     at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)                              
     at net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:29)                     
     at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)              
     at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:108)                 
     at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)                             
     at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)                           
     at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)                    
     at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)     
     at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:157)      
     at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)                    
     at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)                
     at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)            
     at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)                     
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                               
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                               
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                             
     at java.base/java.lang.reflect.Method.invoke(Unknown Source)                                          
     at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)                                             
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                               
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                               
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                             
     at java.base/java.lang.reflect.Method.invoke(Unknown Source)                                          
     at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)                                         
     at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)                                   
     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)                                   
     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)                                     
     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)                                
     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)                                  
     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)                                   
     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)                                
     at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)                                      
     at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)                                
     at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)                             
     at org.mozilla.javascript.Context.call(Context.java:554)                                            
     at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)                                     
     at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)                                  
     at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)                                
     at com.sun.proxy.$Proxy4.run(Unknown Source)                                                  
     at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)                                   
     at org.itxtech.mcl.Loader.start(Loader.java:129)                                                
     at org.itxtech.mcl.Loader.main(Loader.java:53) 
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Linux, microsoft-edge-dev.desktop                      
, Only FireFox browser supported now.                                                         
     at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$5(MxSelenium.java:261)                           
     at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:352)                               
     at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)                                
     at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:64)                      
     at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)                        
     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                                             
     at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)                           
     at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)                           
     ... 44 more  
~~~~
请问这样的报错是因为对 linux 和 edge 的不支持导致的么？要如何解决？

**Comment by choucaicai** [comment]
我也报这个错了，请问解决了嘛

**Comment by BesiegedCity** [comment]
```
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Linux, microsoft-edge-dev.desktop                      
, Only FireFox browser supported now.    
``` 
我是Windows下的环境，出现类似错误之后我安装了Chrome(firefox应该也行)，并将其设置为默认浏览器后解决了。
你试试在Linux下把Firefox设置成默认(?

**Comment by XuZhonghao0808** [comment]
大佬怎解决了嘛，我也遇到了

**Comment by Catoverflow** [comment]
没有解决，后来换了平台（
