### ISSUE TITLE
希望能支持MacOS

### ISSUE THREAD

**Issue by jacktang** [project-mirai/mirai-login-solver-selenium#5]
之前测试都是好的，怎么就不行了。。。
```
2020-12-30 21:23:00 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-selenium is not supported.
java.lang.RuntimeException: Exception in loading selenium
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:23)
	at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
	at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:27)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:108)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:155)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Mac OS X
	at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$6(MxSelenium.java:226)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:231)
	at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:121)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:54)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
	at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:22)
	... 16 more
```

**Comment by Karlatemp** [comment]
其实之前也不支持, 请参考 手动解决滑动验证码

**Comment by jacktang** [comment]
我加了`-Dmirai.slider.captcha.supported` 启动参数，还是出来 `Unsupported Platform: Mac OS X`。用的版本是 `2.0-M2-dev-10`。是需要更新到最新版吗？

**Comment by Karlatemp** [comment]
`-Dmirai.slider.captcha.supported` 意为 完全自己完成验证, 添加此参数的时候不需要使用 `mirai-login-solver-selenium`, 并且 `mirai-core` 存在一个问题无法显示验证地址 (#4), 需要同时更新 `mirai-core` 至 `2.0-M2-1`

手动完成验证步骤请参考本项目的 README.md

**Comment by Karlatemp** [comment]
- [ ] TODO: Firefox

**Comment by jacktang** [comment]
@Karlatemp 需要测试随时喊一声
