### ISSUE TITLE
启动mcl时报错：org.mozilla.javascript.WrappedException: Wrapped java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (updater.js#45)

### ISSUE THREAD

**Issue by dbxxx-ac** [project-mirai/mirai-login-solver-selenium#6]
完整报错如下：
` 17:11:38 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (updater.js#45)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script.checkLocalFile(updater.js:45)
        at script.check(updater.js:53)
        at script(updater.js:38)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:93)
        at org.itxtech.mcl.Loader.start(Loader.java:125)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.itxtech.mcl.component.Config$Package.getName(Config.java:101)
        at org.itxtech.mcl.component.Config$Package.getBasename(Config.java:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 18 more`

**Comment by dbxxx-ac** [comment]
这个是在加载 mirai-login-solver-selenium 后出现的报错

**Comment by dbxxx-ac** [comment]
上边是经过mcl的update packages指令后 的结果
之前没update packages，我手动下载，就和没下载一模一样 还是提示滑块验证失败。然后我就用update packages，结果报错变成了帖子所示的那样。

**Comment by dbxxx-ac** [comment]
手动下载应该是下到libs文件夹吧？

**Comment by dbxxx-ac** [comment]
我 sb 了，没下好对应的版本。
