### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported browser 错误

### ISSUE THREAD

**Issue by dbxxx-ac** [project-mirai/mirai-login-solver-selenium#7]
```
2021-01-03 00:35:02 W/Bot.3466211762: java.lang.UnsupportedOperationException: Unsupported browser: AppX90nv6nhay5n6a98fnetv7tpk64pp35es, Only chrome/firefox supportted
java.lang.UnsupportedOperationException: Unsupported browser: AppX90nv6nhay5n6a98fnetv7tpk64pp35es, Only chrome/firefox supportted
        at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize$2(MxSelenium.java:172)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

整个错误是这样的。应该是说我没有下载好支持的浏览器。

但是我已经确保我从官方渠道下载好了chrome，并且重启了cmd，请问为什么仍旧报错？

**Comment by Karlatemp** [comment]
系统设置 / 默认浏览器 / 选择Chrome



---原始邮件---
发件人: "crab-in-the-northeast"<notifications@github.com&gt;
发送时间: 2021年1月3日(周日) 凌晨0:37
收件人: "project-mirai/mirai-login-solver-selenium"<mirai-login-solver-selenium@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [project-mirai/mirai-login-solver-selenium] java.lang.UnsupportedOperationException: Unsupported browser 错误 (#7)




 2021-01-03 00:35:02 W/Bot.3466211762: java.lang.UnsupportedOperationException: Unsupported browser: AppX90nv6nhay5n6a98fnetv7tpk64pp35es, Only chrome/firefox supportted java.lang.UnsupportedOperationException: Unsupported browser: AppX90nv6nhay5n6a98fnetv7tpk64pp35es, Only chrome/firefox supportted         at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize$2(MxSelenium.java:172)         at io.github.karlatemp.mxlib.selenium.MxSelenium.newDriver(MxSelenium.java:226)         at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)         at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:36)         at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolverImpl.kt:18)         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)  
整个错误是这样的。应该是说我没有下载好支持的浏览器。
 
但是我已经确保我从官方渠道下载好了chrome，并且重启了cmd，请问为什么仍旧报错？

**Comment by dbxxx-ac** [comment]
感谢您的回复！
