### ISSUE TITLE
加载过程中报错

### ISSUE THREAD

**Issue by ghost** [project-mirai/mirai-login-solver-selenium#8]
OS = Windows Server 2012 R2
2021-01-08 18:22:39 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-
selenium is not supported.
java.lang.RuntimeException: Exception in loading selenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLogin
SolverImpl.kt:32)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.in
voke(SeleniumLoginSolver.kt:17)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.in
voke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLogi
nSolver.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(Seleniu
mLoginSolverPluginMode.kt:29)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnL
oad$mirai_console(JvmPluginInternal.kt:196)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.lo
ad(BuiltInJvmPluginLoaderImpl.kt:108)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPl
uginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPl
uginLoader.kt:36)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginN
oEnable(PluginManagerImpl.kt:85)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPlug
insUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS
tart$mirai_console(MiraiConsoleImplementationBridge.kt:155)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi
raiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira
iConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22
6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169
2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357
8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j
ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap
ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:
105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j
ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101
)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.UnsupportedOperationException: Unsupported browser: IE.HTTP
S, Only chrome/firefox supported
        at io.github.karlatemp.mxlib.selenium.MxSelenium.lambda$initialize0$4(Mx
Selenium.java:202)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.
java:307)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.j
ava:121)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(Sel
eniumLoginSolverImpl.kt:63)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(Sel
eniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumL
oginSolverImpl.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLogin
SolverImpl.kt:31)
        ... 44 more

**Comment by ghost** [comment]
谷歌浏览器已安装，还是不管用

**Comment by Karlatemp** [comment]
设置 > 默认浏览器
